from typing import Protocol, runtime_checkable, Any


@runtime_checkable
class IProcessService(Protocol):
    def toggle(self) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> bool: ...
    def refresh_status(self) -> None: ...
    def monitor(self) -> None: ...


@runtime_checkable
class IVersionService(Protocol):
    def refresh(self, scope: str = "all") -> None: ...


@runtime_checkable
class IConfigService(Protocol):
    def load(self) -> dict: ...
    def save(self, data: dict | None = None) -> dict: ...
    def get(self, key_path: str, default: Any = None) -> Any: ...
    def set(self, key_path: str, value: Any) -> None: ...


@runtime_checkable
class IPackageService(Protocol):
    def show_version(self, name: str) -> str | None: ...
    def install(
        self, name: str, index_url: str | None = None, upgrade: bool = True
    ) -> dict: ...
@runtime_checkable
class IModelPathService(Protocol):
    """Multi-library contract for ModelPathService."""

    def get_libraries(self) -> list: ...
    def add_library(self, base_path: str, name=None) -> dict: ...
    def remove_library(self, library_id: str) -> bool: ...
    def set_default_library(self, library_id: str) -> bool: ...
    def enable_library(self, library_id: str, enabled: bool = True) -> bool: ...
    def update_library(self, library_id: str, **fields) -> bool: ...
    def find_library_by_base_path(self, base_path: str): ...
    def update_mapping(self, base_path: str) -> bool: ...
    def apply_libraries(self) -> bool: ...
    def migrate_legacy_yaml(self) -> dict: ...
    def load_yaml_data(self) -> dict: ...
    def get_external_path(self) -> str: ...
    def is_disabled(self) -> bool: ...

